"""
    Bundesnetzagentur: Ladesäulenregister

    API des Ladesäulenregisters der Bundesnetzagentur  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.ladestationen.model.station_overview_unique_id_field import (
    StationOverviewUniqueIdField,
)

from deutschland import ladestationen


class TestStationOverviewUniqueIdField(unittest.TestCase):
    """StationOverviewUniqueIdField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStationOverviewUniqueIdField(self):
        """Test StationOverviewUniqueIdField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StationOverviewUniqueIdField()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
