"""
    Bundesnetzagentur: Ladesäulenregister

    API des Ladesäulenregisters der Bundesnetzagentur  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.ladestationen.model.station_overview_features import (
    StationOverviewFeatures,
)
from deutschland.ladestationen.model.station_overview_fields import (
    StationOverviewFields,
)
from deutschland.ladestationen.model.station_overview_spatial_reference import (
    StationOverviewSpatialReference,
)
from deutschland.ladestationen.model.station_overview_transform import (
    StationOverviewTransform,
)
from deutschland.ladestationen.model.station_overview_unique_id_field import (
    StationOverviewUniqueIdField,
)

from deutschland import ladestationen

globals()["StationOverviewFeatures"] = StationOverviewFeatures
globals()["StationOverviewFields"] = StationOverviewFields
globals()["StationOverviewSpatialReference"] = StationOverviewSpatialReference
globals()["StationOverviewTransform"] = StationOverviewTransform
globals()["StationOverviewUniqueIdField"] = StationOverviewUniqueIdField
from deutschland.ladestationen.model.station_overview import StationOverview


class TestStationOverview(unittest.TestCase):
    """StationOverview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStationOverview(self):
        """Test StationOverview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StationOverview()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
