"""
    Bundesnetzagentur: Ladesäulenregister

    API des Ladesäulenregisters der Bundesnetzagentur  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.ladestationen.model.geometry import Geometry

from deutschland import ladestationen

globals()["Geometry"] = Geometry
from deutschland.ladestationen.model.quantization_parameter import QuantizationParameter


class TestQuantizationParameter(unittest.TestCase):
    """QuantizationParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuantizationParameter(self):
        """Test QuantizationParameter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = QuantizationParameter()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
